module.exports = {
    WRITING_IMAGE_INTO_FOLDER_CODE_ERROR: 136,
    EXTRACT_DATA_CODE_ERROR: 137,
    CREATE_ASSOCIATED_TOKEN_ACCOUNT_CODE_ERROR: 138,
    MINT_TOKEN_CODE_ERROR: 139,
    CALCULATE_TOKEN_AMOUNT_CODE_ERROR: 140
}